name: Vladimir Kostyukov
description: "Posts / Slides"
meta_description: ""

highlighter: rouge
paginate: 5
permalink: /posts/:title/

gems: 
  - jekyll-paginate
  - jekyll-feed

feed:
  path: rss.xml

url: 'http://kostyukov.net'
author: 'Vladimir Kostyukov'
